# ===================================================================
# Docker Compose per al projecte Limo amb YOLO (ROS2 Humble)
# ===================================================================
#
# Aquest fitxer construeix la imatge des del Dockerfile local (que conté
# dos workspaces) i llança el contenidor utilitzant l'entrypoint i
# la comanda del workspace original 'limo'.
#
# Per iniciar:
# docker-compose up -d

name: limo_yolo_project

services:
  limo-yolo-container:
    # Construeix la imatge utilitzant el Dockerfile en el directori actual (.)
    build:
      context: .
      dockerfile: Dockerfile
    # Nom que es donarà a la imatge un cop construïda
    image: limo_yolo_humble_image
    # -- Opcions d'execució --
    privileged: true
    network_mode: host
    restart: always
    container_name: limo_yolo_humble_container
    
    # -- Volums --
    # Muntem la configuració i els scripts necessaris per llançar l'entorn original del Limo.
    # Assegura't que els fitxers locals (ex: ./limo_entrypoint-v3.sh) existeixen.
    volumes:
      - /var/lib/theconstruct.rrl/cyclonedds.xml:/var/lib/theconstruct.rrl/cyclonedds.xml
      - /dev:/dev
      - ./limo_base.launch.py:/root/agilex_ws/install/limo_base/share/limo_base/launch/limo_base.launch.py
      - ./limo_start.launch.py:/root/agilex_ws/install/limo_bringup/share/limo_bringup/launch/humble/limo_start.launch.py
      - ./limo_entrypoint.sh:/limo_entrypoint.sh
    
    # -- Comanda d'inici --
    # Utilitzem l'entrypoint i la comanda originals del Limo.
    entrypoint: /limo_entrypoint.sh
    command: ["ros2", "launch", "limo_bringup", "limo_start.launch.py"]

